MIN_SUPPORT = 75/10281
MIN_CONFIDENCE = 0
MIN_LEVEL = 1
MAX_LEVEL = 4
TOTAL_VERTICES = 10281 #12065


def setNumberOfVertices(AllNode):
    global TOTAL_VERTICES
    TOTAL_VERTICES = len(AllNode)
